### ISSUE TITLE
After editing index.js to have var Service,Characteristic module will not load

### ISSUE THREAD

**Issue by jasonmch** [nmelo/homebridge-lifx#2]
Whenever I try to launch home bridge with the Lifx module configured Homebridge fails to load with error:

[LIFx] Initializing LIFx platform...
module.js:339
    throw err;
    ^

Error: Cannot find module 'lifx'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.LIFxPlatform (/opt/local/lib/node_modules/homebridge-lifx/index.js:37:22)
    at Server._loadPlatforms (/opt/local/lib/node_modules/homebridge/lib/server.js:195:32)
    at Server.run (/opt/local/lib/node_modules/homebridge/lib/server.js:35:36)
    at module.exports (/opt/local/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/opt/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)

**Comment by nmelo** [comment]
@jasonmch Fixed by https://github.com/nmelo/homebridge-lifx/commit/65b0397792a5fcddc61dad1181a08428ee7a1298
