### ISSUE TITLE
Possible event listener leak

### ISSUE THREAD

**Issue by nmelo** [nmelo/homebridge-lifx#3]
(node) warning: possible EventEmitter memory leak detected. 11 bulbstate listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Lifx.addListener (events.js:239:17)
    at Object.LIFxBulbAccessory.getLan (/Users/nmelo/.nvm/versions/node/v5.1.0/lib/node_modules/homebridge-lifx/index.js:82:18)
    at null.<anonymous> (/Users/nmelo/.nvm/versions/node/v5.1.0/lib/node_modules/homebridge-lifx/index.js:232:58)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Characteristic.getValue (/Users/nmelo/.nvm/versions/node/v5.1.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)
    at Bridge.<anonymous> (/Users/nmelo/.nvm/versions/node/v5.1.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:438:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/Users/nmelo/.nvm/versions/node/v5.1.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:410:8)
    at emitThree (events.js:97:13)
    at HAPServer.emit (events.js:175:7)

**Comment by devbobo** [comment]
I've got some ideas on how to resolve this....I'll try to spend some time over the weekend

**Comment by devbobo** [comment]
I've submitted a PR that should fix this issue

**Comment by nmelo** [comment]
:+1: Thanks @devbobo
