### ISSUE TITLE
On launch of homebridge events.js throws unhanded error event

### ISSUE THREAD

**Issue by jasonmch** [nmelo/homebridge-lifx#4]
[LIFx] Initializing LIFx platform...
[LIFx] Fetching LIFx devices.
Loading 0 accessories...
**\* UDP error Error: bind EADDRINUSE 0.0.0.0:56700
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:56700
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at dgram.js:213:18
    at doNTCallback3 (node.js:452:9)
    at process._tickCallback (node.js:358:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by nmelo** [comment]
@jasonmch Please post the output of: 

sudo lsof -i :56700

**Comment by jasonmch** [comment]
Ah, I have Indigo up and running and within Indigo I had a lifx plugin enabled also which had taken over 56700.  As soon as I disabled that plugin,  homebridge successfully launched and found my lights.  Devices are presented to HomeKit and are controllable via app but only power state.  Any change in color/saturation/dim are non-functional.

**Comment by nmelo** [comment]
@jasonmch good to know!

**Comment by jbadnes** [comment]
I have a similar problem with a UDP error I get this error when loading.

Load homebridge-lifx-lan.LifxLan
LIFX Client UDP error
Trace: { [Error: bind EADDRINUSE 0.0.0.0:56700]
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 56700 }
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-lifx-lan/node_modules/node-lifx/lib/lifx/client.js:147:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at dgram.js:215:14
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3

My output to sudo lsof -i :56700

is the following

"COMMAND    PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
homebridg 3742 jbandes   10u  IPv4  24671      0t0  UDP *:56700"

I notice that homebridge in this outpute is missing the "e"
